export const strings = {
  app: {
    title: 'Sidequest',
  },
  onboarding: {
    skip: 'Salta',
    next: 'Avanti',
    start: 'Inizia',
    slide1Title: 'Benvenuto su Sidequest',
    slide1Body: 'Scopri missioni rapide per aiutare la tua community e ottenere ricompense immediate.',
    slide2Title: 'Crea o partecipa alle missioni',
    slide2Body: 'Pubblica missioni in pochi passaggi e candidati direttamente dall\'app, senza email.',
  },
  home: {
    welcome: 'Pronto per una nuova missione?',
    createMission: 'Crea missione',
    createMissionSubtitle: 'Avvia un incarico in pochi step guidati.',
    joinMission: 'Partecipa a missione',
    joinMissionSubtitle: 'Sfoglia le missioni aperte vicino a te.',
    joinEvents: 'Partecipa a eventi',
    joinEventsSubtitle: 'Scopri opportunità speciali dalla community.',
    requestLocation: 'Concedi posizione',
    profileIconLabel: 'Apri profilo',
    locationGranted: 'Posizione abilitata',
    locationDenied: 'Permesso negato',
  },
  missions: {
    listTitle: 'Missioni disponibili',
    filtersLabel: 'Filtri missioni',
    filterAll: 'Tutte',
    emptyState: 'Nessuna missione trovata. Prova a cambiare filtro.',
    loadError: 'Impossibile caricare le missioni. Ritenta più tardi.',
    detailCta: 'Candidati',
    rewardLabel: 'Ricompensa',
    locationLabel: 'Luogo',
    dateLabel: 'Data',
    tagsLabel: 'Tag',
    contactVisible: 'Contatto missione',
    candidateSuccess: 'Candidatura inviata! Ti faremo sapere.',
    candidateError: 'Errore durante la candidatura.',
    previewLabel: 'Anteprima missione',
  },
  create: {
    sheetTitle: 'Nuova missione',
    next: 'Prosegui',
    back: 'Indietro',
    publish: 'Pubblica missione',
    cancel: 'Annulla',
    success: 'Missione pubblicata con successo!',
    error: 'Errore nel salvataggio della missione.',
    step1Title: 'Dettagli principali',
    step1Subtitle: 'Titolo e descrizione della missione.',
    step2Title: 'Luogo e data',
    step2Subtitle: 'Quando e dove avverrà la missione.',
    step3Title: 'Ricompensa e tag',
    step3Subtitle: 'Incentivi e parole chiave per farsi trovare.',
    step4Title: 'Riepilogo',
    step4Subtitle: 'Controlla prima di pubblicare.',
    titleLabel: 'Titolo',
    descriptionLabel: 'Descrizione',
    locationLabel: 'Luogo',
    dateLabel: 'Data',
    rewardLabel: 'Ricompensa',
    tagsLabel: 'Tag (separa con virgole)',
    contactLabel: 'Contatto visibile',
    reviewHeading: 'Rivedi la tua missione',
    titleMinLength: 'Il titolo deve contenere almeno 4 caratteri.',
    offlineTitle: 'Demo offline',
    offlineMessage: 'Demo: missione creata offline (non persistita).',
  },
  applications: {
    sheetTitle: 'Candidatura',
    nameLabel: 'Nome (opzionale)',
    contactLabel: 'Contatto preferito',
    noteLabel: 'Nota per il creator',
    submit: 'Invia candidatura',
    contactHint: 'Telefono o email preferiti (opzionale).',
    success: 'Candidatura registrata!',
    successTitle: 'Grazie!',
    offlineTitle: 'Demo offline',
    offlineMessage: 'Demo: candidatura simulata (offline).',
    error: 'Errore durante l\'invio.',
  },
  profile: {
    title: 'Profilo',
    deviceIdLabel: 'ID dispositivo',
    myMissions: 'Le mie missioni',
    myApplications: 'Le mie candidature',
    resetDemo: 'Reimposta dati demo locali',
    resetConfirmation: 'Dati demo ripristinati.',
    emptyMissions: 'Non hai missioni create.',
    emptyApplications: 'Non hai candidature inviate.',
  },
  events: {
    title: 'Eventi in arrivo',
    description: 'Partecipa a workshop e incontri della community.',
    empty: 'Stiamo preparando nuovi eventi, torna presto!',
  },
  accessibility: {
    requiredField: 'Campo obbligatorio',
    validationError: 'Controlla i campi evidenziati.',
    close: 'Chiudi',
  },
  feedback: {
    offlineFallback: 'Modalità offline attiva. Stai visualizzando dati locali.',
  },
};

export type Strings = typeof strings;
